/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-06-02 06:42:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class predictPremiumDB_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.20.jar", Long.valueOf(1652254202000L));
    _jspx_dependants.put("jar:file:/C:/Users/yash%20shukla/.m2/repository/org/springframework/spring-webmvc/5.3.20/spring-webmvc-5.3.20.jar!/META-INF/spring-form.tld", Long.valueOf(1652232424000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
    _jspx_dependants.put("jar:file:/C:/Users/yash%20shukla/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005faction.release();
    _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Add Health Information</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">Health App</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">Home <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">About</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">Contact</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container mt-5\">\r\n");
      out.write("        <h2 class=\"mb-4\">Add Health Information</h2>\r\n");
      out.write("        ");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f0_reused = false;
    try {
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /WEB-INF/views/predictPremiumDB.jsp(36,8) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction("addAndPredict");
      // /WEB-INF/views/predictPremiumDB.jsp(36,8) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setModelAttribute("PremiumEntity");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            <div class=\"form-group row\">\r\n");
            out.write("                ");
            if (_jspx_meth_form_005flabel_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                <div class=\"col-sm-4\">\r\n");
            out.write("                    ");
            if (_jspx_meth_form_005finput_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                </div>\r\n");
            out.write("                ");
            if (_jspx_meth_form_005flabel_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                <div class=\"col-sm-4\">\r\n");
            out.write("                    ");
            if (_jspx_meth_form_005finput_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"form-group row\">\r\n");
            out.write("                ");
            if (_jspx_meth_form_005flabel_005f2(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                <div class=\"col-sm-4\">\r\n");
            out.write("                    ");
            if (_jspx_meth_form_005finput_005f2(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                </div>\r\n");
            out.write("                ");
            if (_jspx_meth_form_005flabel_005f3(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                <div class=\"col-sm-4\">\r\n");
            out.write("                    ");
            if (_jspx_meth_form_005finput_005f3(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"form-group row\">\r\n");
            out.write("                ");
            if (_jspx_meth_form_005flabel_005f4(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                <div class=\"col-sm-4\">\r\n");
            out.write("                    ");
            if (_jspx_meth_form_005finput_005f4(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                </div>\r\n");
            out.write("                ");
            if (_jspx_meth_form_005flabel_005f5(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                <div class=\"col-sm-4\">\r\n");
            out.write("                    ");
            if (_jspx_meth_form_005finput_005f5(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"form-group row\">\r\n");
            out.write("                ");
            if (_jspx_meth_form_005flabel_005f6(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                <div class=\"col-sm-4\">\r\n");
            out.write("                    ");
            if (_jspx_meth_form_005finput_005f6(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                </div>\r\n");
            out.write("                ");
            if (_jspx_meth_form_005flabel_005f7(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                <div class=\"col-sm-4\">\r\n");
            out.write("                    ");
            if (_jspx_meth_form_005finput_005f7(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"form-group row\">\r\n");
            out.write("                ");
            if (_jspx_meth_form_005flabel_005f8(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                <div class=\"col-sm-4\">\r\n");
            out.write("                    ");
            if (_jspx_meth_form_005finput_005f8(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                </div>\r\n");
            out.write("                ");
            if (_jspx_meth_form_005flabel_005f9(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                <div class=\"col-sm-4\">\r\n");
            out.write("                    ");
            if (_jspx_meth_form_005finput_005f9(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"form-group row\">\r\n");
            out.write("                <div class=\"col-sm-12 text-right\">\r\n");
            out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Submit</button>\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005faction.reuse(_jspx_th_form_005fform_005f0);
      _jspx_th_form_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_form_005flabel_005f0 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_form_005flabel_005f0_reused = false;
    try {
      _jspx_th_form_005flabel_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005flabel_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(38,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005flabel_005f0.setPath("age");
      // /WEB-INF/views/predictPremiumDB.jsp(38,16) null
      _jspx_th_form_005flabel_005f0.setDynamicAttribute(null, "class", "col-sm-2 col-form-label");
      int[] _jspx_push_body_count_form_005flabel_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005flabel_005f0 = _jspx_th_form_005flabel_005f0.doStartTag();
        if (_jspx_eval_form_005flabel_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Age:");
            int evalDoAfterBody = _jspx_th_form_005flabel_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005flabel_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005flabel_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005flabel_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005flabel_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.reuse(_jspx_th_form_005flabel_005f0);
      _jspx_th_form_005flabel_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005flabel_005f0, _jsp_getInstanceManager(), _jspx_th_form_005flabel_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_form_005finput_005f0_reused = false;
    try {
      _jspx_th_form_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(40,20) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f0.setPath("age");
      // /WEB-INF/views/predictPremiumDB.jsp(40,20) null
      _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "type", "number");
      // /WEB-INF/views/predictPremiumDB.jsp(40,20) null
      _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "class", "form-control");
      // /WEB-INF/views/predictPremiumDB.jsp(40,20) null
      _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "required", "true");
      int[] _jspx_push_body_count_form_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f0 = _jspx_th_form_005finput_005f0.doStartTag();
        if (_jspx_th_form_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f0);
      _jspx_th_form_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_form_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_form_005flabel_005f1 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_form_005flabel_005f1_reused = false;
    try {
      _jspx_th_form_005flabel_005f1.setPageContext(_jspx_page_context);
      _jspx_th_form_005flabel_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(42,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005flabel_005f1.setPath("diabetes");
      // /WEB-INF/views/predictPremiumDB.jsp(42,16) null
      _jspx_th_form_005flabel_005f1.setDynamicAttribute(null, "class", "col-sm-2 col-form-label");
      int[] _jspx_push_body_count_form_005flabel_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_form_005flabel_005f1 = _jspx_th_form_005flabel_005f1.doStartTag();
        if (_jspx_eval_form_005flabel_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Diabetes:");
            int evalDoAfterBody = _jspx_th_form_005flabel_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005flabel_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005flabel_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005flabel_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005flabel_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.reuse(_jspx_th_form_005flabel_005f1);
      _jspx_th_form_005flabel_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005flabel_005f1, _jsp_getInstanceManager(), _jspx_th_form_005flabel_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_form_005finput_005f1_reused = false;
    try {
      _jspx_th_form_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(44,20) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f1.setPath("diabetes");
      // /WEB-INF/views/predictPremiumDB.jsp(44,20) null
      _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "type", "text");
      // /WEB-INF/views/predictPremiumDB.jsp(44,20) null
      _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "class", "form-control");
      // /WEB-INF/views/predictPremiumDB.jsp(44,20) null
      _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "required", "true");
      int[] _jspx_push_body_count_form_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f1 = _jspx_th_form_005finput_005f1.doStartTag();
        if (_jspx_th_form_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f1);
      _jspx_th_form_005finput_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005finput_005f1, _jsp_getInstanceManager(), _jspx_th_form_005finput_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_form_005flabel_005f2 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_form_005flabel_005f2_reused = false;
    try {
      _jspx_th_form_005flabel_005f2.setPageContext(_jspx_page_context);
      _jspx_th_form_005flabel_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(48,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005flabel_005f2.setPath("anyTransplants");
      // /WEB-INF/views/predictPremiumDB.jsp(48,16) null
      _jspx_th_form_005flabel_005f2.setDynamicAttribute(null, "class", "col-sm-2 col-form-label");
      int[] _jspx_push_body_count_form_005flabel_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_form_005flabel_005f2 = _jspx_th_form_005flabel_005f2.doStartTag();
        if (_jspx_eval_form_005flabel_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Any Transplants:");
            int evalDoAfterBody = _jspx_th_form_005flabel_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005flabel_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005flabel_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005flabel_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005flabel_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.reuse(_jspx_th_form_005flabel_005f2);
      _jspx_th_form_005flabel_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005flabel_005f2, _jsp_getInstanceManager(), _jspx_th_form_005flabel_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_form_005finput_005f2_reused = false;
    try {
      _jspx_th_form_005finput_005f2.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(50,20) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f2.setPath("anyTransplants");
      // /WEB-INF/views/predictPremiumDB.jsp(50,20) null
      _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "type", "text");
      // /WEB-INF/views/predictPremiumDB.jsp(50,20) null
      _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "class", "form-control");
      // /WEB-INF/views/predictPremiumDB.jsp(50,20) null
      _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "required", "true");
      int[] _jspx_push_body_count_form_005finput_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f2 = _jspx_th_form_005finput_005f2.doStartTag();
        if (_jspx_th_form_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f2);
      _jspx_th_form_005finput_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005finput_005f2, _jsp_getInstanceManager(), _jspx_th_form_005finput_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_form_005flabel_005f3 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_form_005flabel_005f3_reused = false;
    try {
      _jspx_th_form_005flabel_005f3.setPageContext(_jspx_page_context);
      _jspx_th_form_005flabel_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(52,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005flabel_005f3.setPath("anyChronicDiseases");
      // /WEB-INF/views/predictPremiumDB.jsp(52,16) null
      _jspx_th_form_005flabel_005f3.setDynamicAttribute(null, "class", "col-sm-2 col-form-label");
      int[] _jspx_push_body_count_form_005flabel_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_form_005flabel_005f3 = _jspx_th_form_005flabel_005f3.doStartTag();
        if (_jspx_eval_form_005flabel_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Any Chronic Diseases:");
            int evalDoAfterBody = _jspx_th_form_005flabel_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005flabel_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005flabel_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005flabel_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005flabel_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.reuse(_jspx_th_form_005flabel_005f3);
      _jspx_th_form_005flabel_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005flabel_005f3, _jsp_getInstanceManager(), _jspx_th_form_005flabel_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_form_005finput_005f3_reused = false;
    try {
      _jspx_th_form_005finput_005f3.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(54,20) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f3.setPath("anyChronicDiseases");
      // /WEB-INF/views/predictPremiumDB.jsp(54,20) null
      _jspx_th_form_005finput_005f3.setDynamicAttribute(null, "type", "text");
      // /WEB-INF/views/predictPremiumDB.jsp(54,20) null
      _jspx_th_form_005finput_005f3.setDynamicAttribute(null, "class", "form-control");
      // /WEB-INF/views/predictPremiumDB.jsp(54,20) null
      _jspx_th_form_005finput_005f3.setDynamicAttribute(null, "required", "true");
      int[] _jspx_push_body_count_form_005finput_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f3 = _jspx_th_form_005finput_005f3.doStartTag();
        if (_jspx_th_form_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f3);
      _jspx_th_form_005finput_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005finput_005f3, _jsp_getInstanceManager(), _jspx_th_form_005finput_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_form_005flabel_005f4 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_form_005flabel_005f4_reused = false;
    try {
      _jspx_th_form_005flabel_005f4.setPageContext(_jspx_page_context);
      _jspx_th_form_005flabel_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(58,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005flabel_005f4.setPath("height");
      // /WEB-INF/views/predictPremiumDB.jsp(58,16) null
      _jspx_th_form_005flabel_005f4.setDynamicAttribute(null, "class", "col-sm-2 col-form-label");
      int[] _jspx_push_body_count_form_005flabel_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_form_005flabel_005f4 = _jspx_th_form_005flabel_005f4.doStartTag();
        if (_jspx_eval_form_005flabel_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Height:");
            int evalDoAfterBody = _jspx_th_form_005flabel_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005flabel_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005flabel_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005flabel_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005flabel_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.reuse(_jspx_th_form_005flabel_005f4);
      _jspx_th_form_005flabel_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005flabel_005f4, _jsp_getInstanceManager(), _jspx_th_form_005flabel_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f4 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_form_005finput_005f4_reused = false;
    try {
      _jspx_th_form_005finput_005f4.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(60,20) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f4.setPath("height");
      // /WEB-INF/views/predictPremiumDB.jsp(60,20) null
      _jspx_th_form_005finput_005f4.setDynamicAttribute(null, "type", "text");
      // /WEB-INF/views/predictPremiumDB.jsp(60,20) null
      _jspx_th_form_005finput_005f4.setDynamicAttribute(null, "class", "form-control");
      // /WEB-INF/views/predictPremiumDB.jsp(60,20) null
      _jspx_th_form_005finput_005f4.setDynamicAttribute(null, "required", "true");
      int[] _jspx_push_body_count_form_005finput_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f4 = _jspx_th_form_005finput_005f4.doStartTag();
        if (_jspx_th_form_005finput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f4);
      _jspx_th_form_005finput_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005finput_005f4, _jsp_getInstanceManager(), _jspx_th_form_005finput_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_form_005flabel_005f5 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_form_005flabel_005f5_reused = false;
    try {
      _jspx_th_form_005flabel_005f5.setPageContext(_jspx_page_context);
      _jspx_th_form_005flabel_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(62,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005flabel_005f5.setPath("weight");
      // /WEB-INF/views/predictPremiumDB.jsp(62,16) null
      _jspx_th_form_005flabel_005f5.setDynamicAttribute(null, "class", "col-sm-2 col-form-label");
      int[] _jspx_push_body_count_form_005flabel_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_form_005flabel_005f5 = _jspx_th_form_005flabel_005f5.doStartTag();
        if (_jspx_eval_form_005flabel_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Weight:");
            int evalDoAfterBody = _jspx_th_form_005flabel_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005flabel_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005flabel_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005flabel_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005flabel_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.reuse(_jspx_th_form_005flabel_005f5);
      _jspx_th_form_005flabel_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005flabel_005f5, _jsp_getInstanceManager(), _jspx_th_form_005flabel_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f5 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_form_005finput_005f5_reused = false;
    try {
      _jspx_th_form_005finput_005f5.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(64,20) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f5.setPath("weight");
      // /WEB-INF/views/predictPremiumDB.jsp(64,20) null
      _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "type", "text");
      // /WEB-INF/views/predictPremiumDB.jsp(64,20) null
      _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "class", "form-control");
      // /WEB-INF/views/predictPremiumDB.jsp(64,20) null
      _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "required", "true");
      int[] _jspx_push_body_count_form_005finput_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f5 = _jspx_th_form_005finput_005f5.doStartTag();
        if (_jspx_th_form_005finput_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f5);
      _jspx_th_form_005finput_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005finput_005f5, _jsp_getInstanceManager(), _jspx_th_form_005finput_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_form_005flabel_005f6 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_form_005flabel_005f6_reused = false;
    try {
      _jspx_th_form_005flabel_005f6.setPageContext(_jspx_page_context);
      _jspx_th_form_005flabel_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(68,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005flabel_005f6.setPath("knownAllergies");
      // /WEB-INF/views/predictPremiumDB.jsp(68,16) null
      _jspx_th_form_005flabel_005f6.setDynamicAttribute(null, "class", "col-sm-2 col-form-label");
      int[] _jspx_push_body_count_form_005flabel_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_form_005flabel_005f6 = _jspx_th_form_005flabel_005f6.doStartTag();
        if (_jspx_eval_form_005flabel_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Known Allergies:");
            int evalDoAfterBody = _jspx_th_form_005flabel_005f6.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005flabel_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005flabel_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005flabel_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005flabel_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.reuse(_jspx_th_form_005flabel_005f6);
      _jspx_th_form_005flabel_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005flabel_005f6, _jsp_getInstanceManager(), _jspx_th_form_005flabel_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f6 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_form_005finput_005f6_reused = false;
    try {
      _jspx_th_form_005finput_005f6.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(70,20) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f6.setPath("knownAllergies");
      // /WEB-INF/views/predictPremiumDB.jsp(70,20) null
      _jspx_th_form_005finput_005f6.setDynamicAttribute(null, "type", "text");
      // /WEB-INF/views/predictPremiumDB.jsp(70,20) null
      _jspx_th_form_005finput_005f6.setDynamicAttribute(null, "class", "form-control");
      // /WEB-INF/views/predictPremiumDB.jsp(70,20) null
      _jspx_th_form_005finput_005f6.setDynamicAttribute(null, "required", "true");
      int[] _jspx_push_body_count_form_005finput_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f6 = _jspx_th_form_005finput_005f6.doStartTag();
        if (_jspx_th_form_005finput_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f6);
      _jspx_th_form_005finput_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005finput_005f6, _jsp_getInstanceManager(), _jspx_th_form_005finput_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_form_005flabel_005f7 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_form_005flabel_005f7_reused = false;
    try {
      _jspx_th_form_005flabel_005f7.setPageContext(_jspx_page_context);
      _jspx_th_form_005flabel_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(72,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005flabel_005f7.setPath("historyOfCancerInFamily");
      // /WEB-INF/views/predictPremiumDB.jsp(72,16) null
      _jspx_th_form_005flabel_005f7.setDynamicAttribute(null, "class", "col-sm-2 col-form-label");
      int[] _jspx_push_body_count_form_005flabel_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_form_005flabel_005f7 = _jspx_th_form_005flabel_005f7.doStartTag();
        if (_jspx_eval_form_005flabel_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("History of Cancer in Family:");
            int evalDoAfterBody = _jspx_th_form_005flabel_005f7.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005flabel_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005flabel_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005flabel_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005flabel_005f7.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.reuse(_jspx_th_form_005flabel_005f7);
      _jspx_th_form_005flabel_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005flabel_005f7, _jsp_getInstanceManager(), _jspx_th_form_005flabel_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f7 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_form_005finput_005f7_reused = false;
    try {
      _jspx_th_form_005finput_005f7.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(74,20) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f7.setPath("historyOfCancerInFamily");
      // /WEB-INF/views/predictPremiumDB.jsp(74,20) null
      _jspx_th_form_005finput_005f7.setDynamicAttribute(null, "type", "text");
      // /WEB-INF/views/predictPremiumDB.jsp(74,20) null
      _jspx_th_form_005finput_005f7.setDynamicAttribute(null, "class", "form-control");
      // /WEB-INF/views/predictPremiumDB.jsp(74,20) null
      _jspx_th_form_005finput_005f7.setDynamicAttribute(null, "required", "true");
      int[] _jspx_push_body_count_form_005finput_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f7 = _jspx_th_form_005finput_005f7.doStartTag();
        if (_jspx_th_form_005finput_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f7.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f7);
      _jspx_th_form_005finput_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005finput_005f7, _jsp_getInstanceManager(), _jspx_th_form_005finput_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_form_005flabel_005f8 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_form_005flabel_005f8_reused = false;
    try {
      _jspx_th_form_005flabel_005f8.setPageContext(_jspx_page_context);
      _jspx_th_form_005flabel_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(78,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005flabel_005f8.setPath("numberOfMajorSurgeries");
      // /WEB-INF/views/predictPremiumDB.jsp(78,16) null
      _jspx_th_form_005flabel_005f8.setDynamicAttribute(null, "class", "col-sm-2 col-form-label");
      int[] _jspx_push_body_count_form_005flabel_005f8 = new int[] { 0 };
      try {
        int _jspx_eval_form_005flabel_005f8 = _jspx_th_form_005flabel_005f8.doStartTag();
        if (_jspx_eval_form_005flabel_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Number of Major Surgeries:");
            int evalDoAfterBody = _jspx_th_form_005flabel_005f8.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005flabel_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005flabel_005f8[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005flabel_005f8.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005flabel_005f8.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.reuse(_jspx_th_form_005flabel_005f8);
      _jspx_th_form_005flabel_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005flabel_005f8, _jsp_getInstanceManager(), _jspx_th_form_005flabel_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f8 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_form_005finput_005f8_reused = false;
    try {
      _jspx_th_form_005finput_005f8.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(80,20) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f8.setPath("numberOfMajorSurgeries");
      // /WEB-INF/views/predictPremiumDB.jsp(80,20) null
      _jspx_th_form_005finput_005f8.setDynamicAttribute(null, "type", "number");
      // /WEB-INF/views/predictPremiumDB.jsp(80,20) null
      _jspx_th_form_005finput_005f8.setDynamicAttribute(null, "class", "form-control");
      // /WEB-INF/views/predictPremiumDB.jsp(80,20) null
      _jspx_th_form_005finput_005f8.setDynamicAttribute(null, "required", "true");
      int[] _jspx_push_body_count_form_005finput_005f8 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f8 = _jspx_th_form_005finput_005f8.doStartTag();
        if (_jspx_th_form_005finput_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f8[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f8.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f8.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f8);
      _jspx_th_form_005finput_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005finput_005f8, _jsp_getInstanceManager(), _jspx_th_form_005finput_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005flabel_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_form_005flabel_005f9 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_form_005flabel_005f9_reused = false;
    try {
      _jspx_th_form_005flabel_005f9.setPageContext(_jspx_page_context);
      _jspx_th_form_005flabel_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(82,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005flabel_005f9.setPath("bloodPressureProblems");
      // /WEB-INF/views/predictPremiumDB.jsp(82,16) null
      _jspx_th_form_005flabel_005f9.setDynamicAttribute(null, "class", "col-sm-2 col-form-label");
      int[] _jspx_push_body_count_form_005flabel_005f9 = new int[] { 0 };
      try {
        int _jspx_eval_form_005flabel_005f9 = _jspx_th_form_005flabel_005f9.doStartTag();
        if (_jspx_eval_form_005flabel_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Blood Pressure Problems:");
            int evalDoAfterBody = _jspx_th_form_005flabel_005f9.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005flabel_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005flabel_005f9[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005flabel_005f9.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005flabel_005f9.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005flabel_0026_005fpath_005fclass.reuse(_jspx_th_form_005flabel_005f9);
      _jspx_th_form_005flabel_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005flabel_005f9, _jsp_getInstanceManager(), _jspx_th_form_005flabel_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f9 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_form_005finput_005f9_reused = false;
    try {
      _jspx_th_form_005finput_005f9.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/predictPremiumDB.jsp(84,20) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f9.setPath("bloodPressureProblems");
      // /WEB-INF/views/predictPremiumDB.jsp(84,20) null
      _jspx_th_form_005finput_005f9.setDynamicAttribute(null, "type", "number");
      // /WEB-INF/views/predictPremiumDB.jsp(84,20) null
      _jspx_th_form_005finput_005f9.setDynamicAttribute(null, "class", "form-control");
      // /WEB-INF/views/predictPremiumDB.jsp(84,20) null
      _jspx_th_form_005finput_005f9.setDynamicAttribute(null, "required", "true");
      int[] _jspx_push_body_count_form_005finput_005f9 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f9 = _jspx_th_form_005finput_005f9.doStartTag();
        if (_jspx_th_form_005finput_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f9[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f9.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f9.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f9);
      _jspx_th_form_005finput_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005finput_005f9, _jsp_getInstanceManager(), _jspx_th_form_005finput_005f9_reused);
    }
    return false;
  }
}
